/**
 * Tab snapshots.
 *
 * One mechanism serves four features: sleeping tabs, workspace restore,
 * split-drag freeze, and the tab-switch placeholder. Snapshots are served over
 * a custom `tabshot://` protocol so the store only ever holds an id — never
 * image bytes (see the blueprint, L4).
 */

import { app, protocol, type WebContentsView } from 'electron'
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import type { TabId } from '@shared/types'

export const TABSHOT_SCHEME = 'tabshot'

let dir = ''

/** Must run before app.whenReady(). */
export function registerSnapshotScheme(): void {
  protocol.registerSchemesAsPrivileged([
    {
      scheme: TABSHOT_SCHEME,
      privileges: { standard: true, secure: true, supportFetchAPI: true, bypassCSP: false }
    }
  ])
}

/** Must run after app.whenReady(). */
export function initSnapshots(): void {
  dir = join(app.getPath('userData'), 'snapshots')
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })

  protocol.handle(TABSHOT_SCHEME, async (request) => {
    const id = new URL(request.url).hostname
    const file = pathFor(id)
    if (!id || !existsSync(file)) return new Response(null, { status: 404 })
    try {
      const buf = readFileSync(file)
      return new Response(new Uint8Array(buf), {
        status: 200,
        headers: { 'content-type': 'image/jpeg', 'cache-control': 'no-cache' }
      })
    } catch {
      return new Response(null, { status: 500 })
    }
  })
}

function pathFor(tabId: string): string {
  // tabIds are generated by us and are [a-z0-9]+ — no traversal possible.
  return join(dir, `${tabId.replace(/[^a-z0-9]/gi, '')}.jpg`)
}

export function snapshotUrl(tabId: TabId, version: number): string {
  return `${TABSHOT_SCHEME}://${tabId}/?v=${version}`
}

/** Capture the current paint of a view. Returns false if nothing was written. */
export async function captureTab(tabId: TabId, view: WebContentsView): Promise<boolean> {
  try {
    if (view.webContents.isDestroyed() || view.webContents.isLoading()) return false
    const image = await view.webContents.capturePage()
    if (image.isEmpty()) return false
    // Half size is plenty for a placeholder and a thumbnail, and keeps 4K sane.
    const size = image.getSize()
    const scaled = image.resize({ width: Math.max(1, Math.round(size.width / 2)) })
    writeFileSync(pathFor(tabId), scaled.toJPEG(72))
    return true
  } catch {
    return false
  }
}

export function removeSnapshot(tabId: TabId): void {
  try {
    rmSync(pathFor(tabId), { force: true })
  } catch {
    /* ignore */
  }
}
